Users header fix
Fiu-Fit/back-office pull request #10
Opened 2023-04-27 17:17 UTC by ianshih2003

2023-04-27 21:38 UTC, ManuSanchez02 requested changes

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +        <div className='px-4 py-5 border-b border-gray-600 px-6'>
Estas aplicando `px-#` 2 veces

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +              <dd className='mt-1 text-sm leading-5 mt-0 col-span-2'>
Estas aplicando `mt-#` 2 veces

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +              <dd className='mt-1 text-sm leading-5 mt-0 col-span-2'>
Estas aplicando `mt-#` 2 veces

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +              <dd className='mt-1 text-sm leading-5 mt-0 col-span-2'>
Estas aplicando `mt-#` 2 veces

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +              <dd className='mt-1 text-sm leading-5 mt-0 col-span-2'>
Estas aplicando `mx-#` 2 veces

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +              <dd className='mt-1 text-sm leading-5 mt-0 col-span-2'>
Estas aplicando `mt-#` 2 veces

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +        <div className='px-4 py-5 border-b border-gray-600 px-6'>
Si usas la extension de tailwind en vscode te lo marca

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/[id]/page.tsx
> +    <div style={{ height: '100%', width: '100%' }}>
Usa clases de tailwind

2023-04-27 21:38 UTC, manusfv commented on app/(dashboard)/users/components/user-card.tsx
> +    <Card>
No es mejor usar una `Table`?

2023-04-27 21:38 UTC, ManuSanchez02 commented on app/(dashboard)/users/components/user-detail-header.tsx
> +          <Button variant='contained' style={{ backgroundColor: '#90caf9' }}>
Usa clases de tailwind

2023-04-27 21:38 UTC, ManuSanchez02 commented on app/(dashboard)/users/components/user-detail-header.tsx
> +            style={{ backgroundColor: 'red' }}
Lo mismo aca

2023-04-27 21:38 UTC, ManuSanchez02 commented on app/(dashboard)/users/components/user-list.tsx
> +    <div style={{ height: 400, width: '60%' }}>
Usa clases de tailwind

2023-04-27 21:38 UTC, ManuSanchez02 commented on components/@mui/material/index.tsx
> +export * from '@mui/material';
Para que es esto?

2023-04-27 21:38 UTC, ManuSanchez02 commented on app/utils/MuiSetup.tsx
> +};
Quedo obsoleto esto, puede ser?

2023-04-27 21:52 UTC, ManuSanchez02 requested changes

2023-04-27 21:52 UTC, ManuSanchez02 commented on app/(dashboard)/layout.tsx
> +        <div className='container w-full h-full'>{children}</div>
Esta clase container hace que el `user-detail-header` no tome todo el width

2023-04-27 22:08 UTC, ianshih2003 commented on components/@mui/material/index.tsx
> +export * from '@mui/material';
Para que todos los componentes de mui sean client

2023-04-27 22:08 UTC, ianshih2003 commented on app/utils/MuiSetup.tsx
> +};
No

2023-05-02 04:09 UTC, ManuSanchez02 approved these changes

2023-05-02 16:02 UTC, merged