User metrics panel
Fiu-Fit/back-office pull request #20
Opened 2023-05-29 05:41 UTC by ManuSanchez02

2023-05-31 04:01 UTC, ianshih2003 requested changes
Nota: RE
Programa mejor la prox, gracias saludos, ina shih

2023-05-31 04:01 UTC, ianshih2003 commented on app/(dashboard)/user-metrics/FilterableCharts/FilterableBarChart.tsx
> +}
lodash

2023-05-31 04:01 UTC, ianshih2003 commented on app/api/metrics/route.ts
> +      params: params,
```suggestion
      params,
```

2023-05-31 04:01 UTC, ianshih2003 commented on app/(dashboard)/user-metrics/FilterableCharts/FilterableBarChart.tsx
> +              datasets: chartData.datasetInfo.map(dataset => ({
```suggestion
              datasets: chartData.datasetInfo.map({chartDataset} => ({
```

2023-05-31 04:28 UTC, ManuSanchez02 commented on app/(dashboard)/user-metrics/FilterableCharts/FilterableBarChart.tsx
> +}
Listo

2023-05-31 04:28 UTC, ManuSanchez02 commented on app/api/metrics/route.ts
> +      params: params,
Listo

2023-05-31 04:28 UTC, ManuSanchez02 commented on app/(dashboard)/user-metrics/FilterableCharts/FilterableBarChart.tsx
> +              datasets: chartData.datasetInfo.map(dataset => ({
Listo

2023-06-01 20:27 UTC, ianshih2003 approved these changes

2023-06-02 00:52 UTC, merged